require:
  - rubocop-rspec

AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: false

# This is a remnant of old SUSE-style alignment for hashes, The table format
# looks more human readable.
Layout/AlignHash:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

# Both my last names contain non-ascii characters :) (license notice)
Style/AsciiComments:
  Enabled: false

# Disable the block length cop for tests.
Metrics/BlockLength:
  Enabled: true
  Exclude:
    - spec/**/*

# The default is just too small. A limit of 100 looks reasonable and many other
# projects (including inside of SUSE) are also using this value.
Metrics/LineLength:
  Max: 100

Metrics/MethodLength:
  Max: 20

# This is a common SUSE configuration value: the performance difference between
# single and double quotes is no longer there, and so it's better to be
# consistent and force only double quotes.
Style/StringLiterals:
  EnforcedStyle: double_quotes

# Same as Style/StringLiterals.
Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

# Sometimes we need more than one "expect" command to build our actual
# expectation.
RSpec/MultipleExpectations:
  Max: 6

# Setting a more reasonable value.
RSpec/ExampleLength:
  Max: 10

# Otherwise CConfig is not allowed ...
RSpec/FilePath:
  Enabled: false
