language: ruby
dist: trusty
sudo: false

rvm:
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - 2.7
  - ruby-head

script:
  - bundle exec rspec
  - bundle exec rubocop -V
  - bundle exec rubocop -F

matrix:
  allow_failures:
    - rvm: ruby-head
  fast_finish: true
