language: ruby

cache: bundler

sudo: false

rvm:
  - 2.1
  - 2.2
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - ruby-head

before_install:
  - gem update --system

script:
  - bundle exec rspec
  - bundle exec rubocop -V
  - bundle exec rubocop -F

matrix:
  allow_failures:
    - rvm: ruby-head
  fast_finish: true
